[package]
name = "mixal"
version = "0.1.0"
authors = ["zachross015 <zachross015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
rand = "*"

[[bin]]
name = "mixal"
path = "src/main.rs"
